### ISSUE TITLE
when I use this extension in mediawiki_1.39.1 ,it seems does not work!

### ISSUE THREAD

**Issue by zhengxiaodong-sh** [mgeb/mediawiki-drawio-editor#33]
here is the log，

[f08c93bb94f864da196b0c84] /mediawiki/index.php?title=%E9%A6%96%E9%A1%B5 Error: Call to undefined function wfFindFile()

Backtrace:

from /volume1/web_packages/mediawiki/extensions/DrawioEditor/DrawioEditor.php(89)
#0 /volume1/web_packages/mediawiki/includes/parser/Parser.php(3443): DrawioEditor::parse(Parser, string)
#1 /volume1/web_packages/mediawiki/includes/parser/Parser.php(3126): Parser->callParserFunction(PPFrame_Hash, string, array)
#2 /volume1/web_packages/mediawiki/includes/parser/PPFrame_Hash.php(276): Parser->braceSubstitution(array, PPFrame_Hash)
#3 /volume1/web_packages/mediawiki/includes/parser/Parser.php(2955): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)
#4 /volume1/web_packages/mediawiki/includes/parser/Parser.php(1610): Parser->replaceVariables(string)
#5 /volume1/web_packages/mediawiki/includes/parser/Parser.php(724): Parser->internalParse(string)
#6 /volume1/web_packages/mediawiki/includes/content/WikitextContentHandler.php(301): Parser->parse(string, Title, ParserOptions, boolean, boolean, integer)
#7 /volume1/web_packages/mediawiki/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams, ParserOutput)
#8 /volume1/web_packages/mediawiki/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput(WikitextContent, MediaWiki\Content\Renderer\ContentParseParams)
#9 /volume1/web_packages/mediawiki/includes/Revision/RenderedRevision.php(266): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(WikitextContent, Title, integer, ParserOptions, boolean)
#10 /volume1/web_packages/mediawiki/includes/Revision/RenderedRevision.php(237): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#11 /volume1/web_packages/mediawiki/includes/Revision/RevisionRenderer.php(221): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#12 /volume1/web_packages/mediawiki/includes/Revision/RevisionRenderer.php(158): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#13 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#14 /volume1/web_packages/mediawiki/includes/Revision/RenderedRevision.php(199): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#15 /volume1/web_packages/mediawiki/includes/poolcounter/PoolWorkArticleView.php(91): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#16 /volume1/web_packages/mediawiki/includes/poolcounter/PoolWorkArticleViewCurrent.php(97): PoolWorkArticleView->renderRevision()
#17 /volume1/web_packages/mediawiki/includes/poolcounter/PoolCounterWork.php(162): PoolWorkArticleViewCurrent->doWork()
#18 /volume1/web_packages/mediawiki/includes/page/ParserOutputAccess.php(299): PoolCounterWork->execute()
#19 /volume1/web_packages/mediawiki/includes/page/Article.php(714): MediaWiki\Page\ParserOutputAccess->getParserOutput(WikiPage, ParserOptions, MediaWiki\Revision\RevisionStoreCacheRecord, integer)
#20 /volume1/web_packages/mediawiki/includes/page/Article.php(528): Article->generateContentOutput(User, ParserOptions, integer, OutputPage, array)
#21 /volume1/web_packages/mediawiki/includes/actions/ViewAction.php(78): Article->view()
#22 /volume1/web_packages/mediawiki/includes/MediaWiki.php(542): ViewAction->show()
#23 /volume1/web_packages/mediawiki/includes/MediaWiki.php(322): MediaWiki->performAction(Article, Title)
#24 /volume1/web_packages/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#25 /volume1/web_packages/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#26 /volume1/web_packages/mediawiki/index.php(51): MediaWiki->run()
#27 /volume1/web_packages/mediawiki/index.php(46): wfIndexMain()

**Comment by zhengxiaodong-sh** [comment]
The Drawio extension php used parse->disableCache，and   wfFindFile，but it seem not exist.
